# DiT-XL/2 ImageNet 256x256 Configuration

data:
  # 【关键修改 1】指向预处理好的 Latent 目录
  # 之前是: /work/c30778/dataset/imagenet/
  data_path: "/work/c30778/imagenet_rc10_lat/"
  # data_path: "/work/c30778/imagenet_rc10_lat2/"
  image_size: 256
  num_workers: 32  # Latent 读取很快，可以适当增加 worker

model:
  # DiT-XL/2 Config
  input_size: 32      # 256 / 8 (VAE downsample factor)
  patch_size: 2
  in_channels: 4
  hidden_size: 1152
  depth: 28
  num_heads: 16
  learn_sigma: True
  num_classes: 1000

diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  schedule: "cosine" 

training:
  epochs: 400
  batch_size: 128     
  
  lr: 0.0002          # 1e-4
  results_dir: "./results/dit_xl_2_latent-v1-n2-re"
  use_amp: True       # 混合精度
  seed: 42
  log_interval: 1
  save_interval: 1