model:
  img_size: 224
  patch_size: 16
  in_channels: 3
  embed_dim: 768      # ViT-Base
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0

training:
  batch_size: 4096      # Per GPU
  num_epochs: 100
  learning_rate: 1.5e-4
  weight_decay: 0.05
  warmup_epochs: 5
  
  # HiT Specifics
  mask_ratio: 0.75             # 75% 的区域将被加噪，25% 保持 Clean
  gradient_accumulation_steps: 1